### ISSUE TITLE
mark's todo/tocommit

### ISSUE THREAD

**Issue by lestrato** [lestrato/badgepack#1]
### Todo ###
- [ ] Documentation for all apps
- [x] Fix README.md (packaging and installation)
- [ ] Create tests
- [ ] Host dev server
- [ ] Try unpacking server on another persons computer
- [ ] Fix form clean data

---
